const topics: [val: string, desc: string][] = [
  
  ["algebra", "Algebra"],
  ["ancient_civilization", "Ancient Civilization"],
  ["anthropology", "Anthropology"],
  ["archaeology", "Archaeology"],
  ["architecture", "Architecture"],
  ["art_history", "Art History"],
  ["art_instruction", "Art Instruction"],
  ["artists", "Artists"],
  ["autobiographies", "Autobiographies"],
  ["bears", "Bears"],
  ["biology", "Biology"],
  ["business_economics", "Business Economics"],
  ["business_success", "Business Success"],
  ["cats", "Cats"],
  ["chemistry", "Chemistry"],
  ["composers", "Composers"],
  ["computer science", "Computer Science"],
  ["cookbooks", "Cookbooks"],
  ["cooking", "Cooking"],
  ["dance", "Dance"],
  ["design", "Design"],
  ["dogs", "Dogs"],
  ["education", "Education"],
  ["english_language", "English Language"],
  ["entrepreneurship", "Entrepreneurship"],
  ["exercise", "Exercise"],
  ["fantasy", "Fantasy"],
  ["fashion", "Fashion"],
  ["film", "Film"],
  ["finance", "Finance"],
  ["geography", "Geography"],
  ["graphic_design", "Graphic Design"],
  ["historical_fiction", "Historical Fiction"],
  ["history", "History"],
  ["horror", "Horror"],
  ["humor", "Humor"],
  ["kings_and_rulers", "Kings and Rulers"],
  ["kittens", "Kittens"],
  ["literature", "Literature"],
  ["magic", "Magic"],
  ["management", "Management"],
  ["mathematics", "Mathematics"],
  ["mental_health", "Mental Health"],
  ["music_theory", "Music Theory"],
  ["music", "Music"],
  ["mystery_and_detective_stories", "Mystery and Detective Stories"],
  ["nutrition", "Nutrition"],
  ["painting", "Painting"],
  ["photography", "Photography"],
  ["physics", "Physics"],
  ["plays", "Plays"],
  ["poetry", "Poetry"],
  ["politics_and_government", "Politics and Government"],
  ["programming", "Programming"],
  ["psychology", "Psychology"],
  ["puppies", "Puppies"],
  ["romance", "Romance"],
  ["science_fiction", "Science Fiction"],
  ["science", "Science"],
  ["self-help", "Self-help"],
  ["short_stories", "Short Stories"],
  ["thriller", "Thriller"],
  ["women", "Women"],
  ["world_war_ii", "World War II"],
  ["young_adult", "Young Adult"],

];

export default topics; 